export const FRIEND_GET_SUCCESS="FRIEND_GET_SUCCESS";
export const FRIEND_GET_FAIL="FRIEND_GET_FAIL";
export const CURRENT_FRIEND_SELECT='CURRENT_FRIEND_SELECT';
export const MESSAGE_GET_SUCCESS='MESSAGE_GET_SUCCESS';
export const MESSAGE_SEND_SUCCESS='MESSAGE_SEND_SUCCESS';
export const MESSAGE_ALL_GET_SUCCESS='MESSAGE_ALL_GET_SUCCESS';

